### ISSUE TITLE
Enhance project structure 

### ISSUE THREAD

**Issue by danielcdz** [ByteBuildersLabs/StarknetContracts#8]
## Summary
- Create the .github Directory at the root of the project
- Inside .github create a template directory
  - Move the pull request template file to this templates directory
  - Create a new template for issues
    - Use this as an [example](https://github.com/ByteBuildersLabs/ByteBeastsBackend/pull/82/files#diff-74403ef72cb16a919b77b4cd1e9b546a2836a4bfd8e7483d000e3e8af7f62f9b)
- In the root of the project create a docs directory
- Add a  CODE_OF_CONDUCT.md file with just the title
- Add a CONTRIBUTING.md file with just the title

**Comment by JosueBrenes** [comment]
### Hi, I'm Josué Brenes and I'll be working on this issue.
I'm a member of Dojo Coding.

**Estimated time to complete:** 1 day

### Here's how I would solve this issue:

1. **Create the `.github` directory**:  
   At the root of the project, I would create a directory named `.github`. This is typically used to store templates for issues, pull requests, and other GitHub-specific configuration files.

2. **Inside `.github`, create a `templates` directory**:
   - I would move the existing pull request template file into this new `templates` directory.
   - Then, I’d create a new issue template file in the same directory. I’d follow the example provided in the link to ensure it meets the expected format and usability.

3. **Create a `docs` directory in the root of the project**:  
   This directory would serve as a centralized place for all project documentation, making it easier for contributors to find relevant information.

4. **Add a `CODE_OF_CONDUCT.md` file**:  
   In the root directory, I’d create a file named `CODE_OF_CONDUCT.md` containing only the title for now. This file can be completed later with the appropriate code of conduct guidelines.

5. **Add a `CONTRIBUTING.md` file**:  
   Similarly, I’d create a `CONTRIBUTING.md` file with just the title at the root of the project. This file can be expanded later to include contribution guidelines for developers.

**Comment by petersdt** [comment]
I’d like to work on this.

- i would approach the task as followed:


1. Create .github directory: I'll start by creating a new directory named `.github` at the root of the project.

2. Add template directory: Next, I'll add a `templates` subdirectory inside `.github` to organize templates effectively.

3. Move pull request template: If there’s an existing pull request template file, I'll move it to `.github/templates` to keep everything structured.

4. **Create issue template**: Inside `.github/templates`, I'll create a new file named `issue_template.md`. This template will include:
   - **Title**: A description of the issue.
   - **Expected Behavior**: The expected outcome of the feature or bug.
   - **Actual Behavior**: The current outcome showing the issue.
   - **Steps to Reproduce**: Steps to recreate the issue.

5. **Create docs directory**: I'll then create a `docs` folder at the root of the project for documentation.

6. **Add CODE_OF_CONDUCT.md and CONTRIBUTING.md**: Finally, I'll add `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` files in the `docs` folder, each containing just the title as a placeholder.

**Comment by Jemiiah** [comment]
@danielcdz pls can I work on this issue

**Comment by PabloVillaplana** [comment]
1. Create the .github Directory:

At the root of the project, create a new directory named .github.

2. Add a Template Directory for Pull Requests and Issues:

- Inside .github, create a subdirectory named templates.
- Move the existing pull request template file to this templates directory.
- Create a new issue template file in the templates directory using the format below as an example.

3. Create the docs Directory for Project Documentation:

At the root level, create a new directory named docs.

4. Add a Basic CODE_OF_CONDUCT.md File:

Inside docs, add a CODE_OF_CONDUCT.md file with only the title "Code of Conduct."

5. Add a Basic CONTRIBUTING.md File:

Inside docs, add a CONTRIBUTING.md file with only the title "Contributing."

@danielcdz 👀

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

I am a Dojo Coding Member

First, I would create a .github directory in the root of the project to store GitHub-specific files.

Inside the .github directory, I’d create a templates folder to organize the templates.

Next, I would move the existing pull request template file into this templates directory.

I would then create a new issue template file in the templates directory, using the provided example as a guide.

In the root of the project, I’d create a docs directory. Inside docs, I would add two files: CODE_OF_CONDUCT.md with just the title “Code of Conduct” and CONTRIBUTING.md with the title “Contributing.                                                                                

@danielcdz i would love to contribute

**Comment by martinvibes** [comment]
Can I try solving this issue?

1. Structure project files:

- Add .github/templates folder
- Move PR template into it
- Create issue template using the example
- Add docs directory
- Add basic CODE_OF_CONDUCT.md
- Add basic CONTRIBUTING.md


### Requirements:

- Basic Git knowledge
- GitHub familiarity
-  1 hrs of time

### Why you'll love this:

- Easy first contribution
- Clear deliverables
- Improves project organization
- Great for your portfolio
